import { Footer } from '@/components/footer/Index'
import '../globals.css'
import { Header } from '@/components/header/Index'
import { ParamsDetailsProvider } from '@/context/paramsDetailsContext'
import MoreInfor from './page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body >
        <ParamsDetailsProvider>
          <Header />
            <MoreInfor/>
          <Footer />
        </ParamsDetailsProvider>
      </body>
    </html>
  )
}
